### ISSUE TITLE
No video output when frameskip is enabled

### ISSUE THREAD

**Issue by schmurtzm** [jamsilva/chimerasnes#2]
Hi, 
I'm testing Chimerasnes on Miyoo Mini (little linux handheld , SDL1.2) , Chimerasnes works really well on it except if I enable frameskip (auto or manual) : when it's enabled it 's like if the core doesn't send video output anymore.

https://user-images.githubusercontent.com/7110113/229343010-51566e15-2fcc-40bb-b30d-abe0fd0753ff.mp4

Any idea ?

**Comment by jamsilva** [comment]
This is going to be difficult to debug as I don't have this device or any similar to it. I'll see if I can use https://github.com/TriForceX/MiyooCFW with qemu and debug that way.

**Comment by jamsilva** [comment]
Out of curiosity, does lowering the frameskip threshold help? Also, can you check with snes9x2005 and/or snes9x2010 to see if frameskipping works on those - I'm using the same method, so I'd expect it to fail with those too.

**Comment by schmurtzm** [comment]
Hi, OK forget it, I have tested with Snes9x 2005 and 2010 with almost the same result (not a total freeze but very bad result like a slideshow). 
And finally I just realized that it comes from our OSS sound driver which doesn't like frameskip. Once replaced by SDL frameskip is OK.
So we can close it. Thank you !
